# Generated by Django 4.2.7 on 2024-02-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='videos',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
