# Generated by Django 4.2.7 on 2024-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_video_videos_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='videos',
            field=models.FileField(blank=True, null=True, storage='PrivateMediaStorage', upload_to=''),
        ),
    ]
