# Generated by Django 4.2.7 on 2024-02-09 22:19

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_video_url_video_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videos',
            field=models.FileField(blank=True, null=True, storage=courses.models.PrivateMediaStorage(), upload_to=''),
        ),
    ]
