# Generated by Django 4.2.7 on 2024-03-03 19:50

import BiologyA.settings.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_video_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='files',
        ),
        migrations.AddField(
            model_name='image',
            name='images',
            field=models.FileField(blank=True, null=True, storage=BiologyA.settings.base.ImageStorage(), upload_to=''),
        ),
    ]
