# Generated by Django 4.2.7 on 2024-03-05 21:19

import BiologyA.settings.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_instructor_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(blank=True, null=True, storage=BiologyA.settings.base.FileStorage(), upload_to=''),
        ),
    ]
