# Generated by Django 4.2.7 on 2024-03-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_team_alter_course_instructor_delete_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['member_id']},
        ),
        migrations.AddField(
            model_name='team',
            name='member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='rule',
            field=models.CharField(blank=True, choices=[('instructor', 'INSTRUCTOR')], max_length=200, null=True),
        ),
    ]
